// src/components/Header.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState } from "react"
import { SITE_CONFIG } from "@/lib/site-contact"
import styles from "./Header.module.css"

export function Header() {
  const pathname = usePathname()
  const [mobileOpen, setMobileOpen] = useState(false)

  const isActive = (path: string) => pathname === path
  const starts = (prefix: string) => pathname.startsWith(prefix)

  return (
    <header className={styles.siteHeader}>
      <div className={styles.headerContainer}>
        <Link href="/" className={styles.brand} onClick={() => setMobileOpen(false)}>
          <span className={styles.brandName}>{SITE_CONFIG.businessName}</span>
          <span className={styles.brandTagline}>Dr. Jan Duffy, Realtor</span>
        </Link>

        <nav className={styles.desktopNav} aria-label="Main">
          <ul>
            <li className={isActive("/") ? styles.navItemActive : ""}>
              <Link href="/">Home</Link>
            </li>
            <li
              className={`${styles.hasDropdown} ${starts("/homes") || ["/buy-a-home", "/buyer-checklist", "/listings"].includes(pathname) ? styles.navItemActive : ""}`}
            >
              <Link href="/homes-for-sale">Buy</Link>
              <ul className={styles.dropdown}>
                <li>
                  <Link href="/homes-for-sale">Homes for Sale</Link>
                </li>
                <li>
                  <Link href="/buy-a-home">Buyer&apos;s Guide</Link>
                </li>
                <li>
                  <Link href="/buyer-seller-services">Buyer &amp; Seller Services</Link>
                </li>
                <li>
                  <Link href="/buyer-checklist">Buyer Checklist</Link>
                </li>
                <li>
                  <Link href="/listings">All Listings</Link>
                </li>
                <li>
                  <Link href="/investment-properties">Investment Properties</Link>
                </li>
              </ul>
            </li>
            <li
              className={`${styles.hasDropdown} ${["/sell-your-home", "/home-valuation", "/selling-checklist", "/market-analysis"].includes(pathname) ? styles.navItemActive : ""}`}
            >
              <Link href="/sell-your-home">Sell</Link>
              <ul className={styles.dropdown}>
                <li>
                  <Link href="/sell-your-home">Sell Your Home</Link>
                </li>
                <li>
                  <Link href="/home-valuation">Free Home Valuation</Link>
                </li>
                <li>
                  <Link href="/market-analysis">Market Analysis</Link>
                </li>
                <li>
                  <Link href="/buyer-seller-services">Buyer &amp; Seller Services</Link>
                </li>
                <li>
                  <Link href="/selling-checklist">Selling Checklist</Link>
                </li>
              </ul>
            </li>
            <li
              className={`${styles.hasDropdown} ${starts("/neighborhood") || starts("/pewter-valley-estates") || pathname === "/southwest-las-vegas" || starts("/silverado-ranch") || pathname === "/las-vegas-relocation-guide" ? styles.navItemActive : ""}`}
            >
              <Link href="/neighborhood">Areas</Link>
              <ul className={styles.dropdown}>
                <li>
                  <Link href="/neighborhood">Pewter Valley Estates</Link>
                </li>
                <li>
                  <Link href="/silverado-ranch">Silverado Ranch (Henderson)</Link>
                </li>
                <li>
                  <Link href="/southwest-las-vegas">Southwest Las Vegas</Link>
                </li>
                <li>
                  <Link href="/neighborhood-guide">Neighborhood Guide</Link>
                </li>
                <li>
                  <Link href="/neighborhood-insights">Neighborhood Insights (89183)</Link>
                </li>
                <li>
                  <Link href="/photos">Community Photos</Link>
                </li>
                <li>
                  <Link href="/las-vegas-relocation-guide">Relocation Guide</Link>
                </li>
                <li>
                  <Link href="/pewter-valley-estates/amenities">Nearby amenities (Pewter)</Link>
                </li>
                <li>
                  <Link href="/silverado-ranch/getting-around">Commute &amp; transport</Link>
                </li>
                <li>
                  <Link href="/silverado-ranch/attractions">Attractions &amp; day trips</Link>
                </li>
                <li>
                  <Link href="/silverado-ranch/history">Silverado Ranch history</Link>
                </li>
              </ul>
            </li>
            <li
              className={
                isActive("/about") || isActive("/dr-jan-duffy") ? styles.navItemActive : ""
              }
            >
              <Link href="/about">About</Link>
            </li>
            <li className={isActive("/contact") ? styles.navItemActive : ""}>
              <Link href="/contact">Contact</Link>
            </li>
          </ul>
        </nav>

        <a href={`tel:${SITE_CONFIG.phoneTel}`} className={styles.headerCta}>
          <span className={styles.ctaIcon} aria-hidden>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <title>Call</title>
              <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
            </svg>
          </span>
          <span className={styles.ctaText}>{SITE_CONFIG.phone}</span>
        </a>

        <button
          type="button"
          className={styles.mobileToggle}
          onClick={() => setMobileOpen((o) => !o)}
          aria-expanded={mobileOpen}
          aria-label="Toggle menu"
        >
          <span className={`${styles.hamburger} ${mobileOpen ? styles.hamburgerOpen : ""}`} />
        </button>
      </div>

      {mobileOpen ? (
        <nav className={styles.mobileNav} aria-label="Mobile">
          <ul>
            <li>
              <Link href="/" onClick={() => setMobileOpen(false)}>
                Home
              </Link>
            </li>
            <li className={styles.mobileSection}>
              <span className={styles.sectionTitle}>Buy a Home</span>
              <ul>
                <li>
                  <Link href="/homes-for-sale" onClick={() => setMobileOpen(false)}>
                    Homes for Sale
                  </Link>
                </li>
                <li>
                  <Link href="/buy-a-home" onClick={() => setMobileOpen(false)}>
                    Buyer&apos;s Guide
                  </Link>
                </li>
                <li>
                  <Link href="/buyer-checklist" onClick={() => setMobileOpen(false)}>
                    Buyer Checklist
                  </Link>
                </li>
                <li>
                  <Link href="/buyer-seller-services" onClick={() => setMobileOpen(false)}>
                    Buyer &amp; Seller Services
                  </Link>
                </li>
                <li>
                  <Link href="/listings" onClick={() => setMobileOpen(false)}>
                    All Listings
                  </Link>
                </li>
                <li>
                  <Link href="/investment-properties" onClick={() => setMobileOpen(false)}>
                    Investment Properties
                  </Link>
                </li>
              </ul>
            </li>
            <li className={styles.mobileSection}>
              <span className={styles.sectionTitle}>Sell Your Home</span>
              <ul>
                <li>
                  <Link href="/sell-your-home" onClick={() => setMobileOpen(false)}>
                    Sell Your Home
                  </Link>
                </li>
                <li>
                  <Link href="/selling-checklist" onClick={() => setMobileOpen(false)}>
                    Selling Checklist
                  </Link>
                </li>
                <li>
                  <Link href="/home-valuation" onClick={() => setMobileOpen(false)}>
                    Free Home Valuation
                  </Link>
                </li>
                <li>
                  <Link href="/market-analysis" onClick={() => setMobileOpen(false)}>
                    Market Analysis
                  </Link>
                </li>
                <li>
                  <Link href="/buyer-seller-services" onClick={() => setMobileOpen(false)}>
                    Buyer &amp; Seller Services
                  </Link>
                </li>
              </ul>
            </li>
            <li className={styles.mobileSection}>
              <span className={styles.sectionTitle}>Explore Areas</span>
              <ul>
                <li>
                  <Link href="/neighborhood" onClick={() => setMobileOpen(false)}>
                    Pewter Valley Estates
                  </Link>
                </li>
                <li>
                  <Link href="/silverado-ranch" onClick={() => setMobileOpen(false)}>
                    Silverado Ranch (Henderson)
                  </Link>
                </li>
                <li>
                  <Link href="/southwest-las-vegas" onClick={() => setMobileOpen(false)}>
                    Southwest Las Vegas
                  </Link>
                </li>
                <li>
                  <Link href="/neighborhood-guide" onClick={() => setMobileOpen(false)}>
                    Neighborhood Guide
                  </Link>
                </li>
                <li>
                  <Link href="/neighborhood-insights" onClick={() => setMobileOpen(false)}>
                    Neighborhood Insights (89183)
                  </Link>
                </li>
                <li>
                  <Link href="/las-vegas-relocation-guide" onClick={() => setMobileOpen(false)}>
                    Relocation Guide
                  </Link>
                </li>
                <li>
                  <Link href="/photos" onClick={() => setMobileOpen(false)}>
                    Community Photos
                  </Link>
                </li>
                <li>
                  <Link
                    href="/pewter-valley-estates/amenities"
                    onClick={() => setMobileOpen(false)}
                  >
                    Nearby amenities (Pewter)
                  </Link>
                </li>
                <li>
                  <Link href="/silverado-ranch/getting-around" onClick={() => setMobileOpen(false)}>
                    Commute &amp; transport
                  </Link>
                </li>
                <li>
                  <Link href="/silverado-ranch/attractions" onClick={() => setMobileOpen(false)}>
                    Attractions &amp; day trips
                  </Link>
                </li>
                <li>
                  <Link href="/silverado-ranch/history" onClick={() => setMobileOpen(false)}>
                    Silverado Ranch history
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link href="/about" onClick={() => setMobileOpen(false)}>
                About Dr. Jan Duffy
              </Link>
            </li>
            <li>
              <Link href="/faq" onClick={() => setMobileOpen(false)}>
                FAQ
              </Link>
            </li>
            <li>
              <Link href="/contact" onClick={() => setMobileOpen(false)}>
                Contact
              </Link>
            </li>
          </ul>
          <a
            href={`tel:${SITE_CONFIG.phoneTel}`}
            className={styles.mobileCta}
            onClick={() => setMobileOpen(false)}
          >
            <span className={styles.mobileCtaIcon} aria-hidden>
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <title>Call</title>
                <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
              </svg>
            </span>
            Call {SITE_CONFIG.phone}
          </a>
        </nav>
      ) : null}
    </header>
  )
}

// src/lib/header/Header.svelte
<script>
import { slide } from "svelte/transition"
import { page } from "$app/state"
import { SITE_CONFIG } from "$lib/seo.js"

let mobileMenuOpen = $state(false)

function toggleMenu() {
  mobileMenuOpen = !mobileMenuOpen;
}

function closeMenu() {
  mobileMenuOpen = false;
}
</script>

<header class="site-header">
  <div class="header-container">
    <!-- Logo/Brand -->
    <a href="/" class="brand" onclick={closeMenu}>
      <span class="brand-name">{SITE_CONFIG.businessName}</span>
      <span class="brand-tagline">Dr. Jan Duffy, Realtor</span>
    </a>

    <!-- Desktop Navigation -->
    <nav class="desktop-nav">
      <ul>
        <li class:active={page.url.pathname === "/"}>
          <a href="/">Home</a>
        </li>
        <li class="has-dropdown" class:active={page.url.pathname.startsWith("/homes") || page.url.pathname === "/buy-a-home" || page.url.pathname === "/buyer-checklist" || page.url.pathname === "/listings"}>
          <a href="/homes-for-sale">Buy</a>
          <ul class="dropdown">
            <li><a href="/homes-for-sale">Homes for Sale</a></li>
            <li><a href="/buy-a-home">Buyer's Guide</a></li>
            <li><a href="/buyer-checklist">Buyer Checklist</a></li>
            <li><a href="/listings">All Listings</a></li>
            <li><a href="/investment-properties">Investment Properties</a></li>
          </ul>
        </li>
        <li class="has-dropdown" class:active={page.url.pathname === "/sell-your-home" || page.url.pathname === "/home-valuation" || page.url.pathname === "/selling-checklist"}>
          <a href="/sell-your-home">Sell</a>
          <ul class="dropdown">
            <li><a href="/sell-your-home">Sell Your Home</a></li>
            <li><a href="/home-valuation">Free Home Valuation</a></li>
            <li><a href="/market-analysis">Market Analysis</a></li>
            <li><a href="/selling-checklist">Selling Checklist</a></li>
          </ul>
        </li>
        <li class="has-dropdown" class:active={page.url.pathname.startsWith("/neighborhood") || page.url.pathname.startsWith("/pewter-valley-estates") || page.url.pathname === "/southwest-las-vegas" || page.url.pathname.startsWith("/silverado-ranch") || page.url.pathname === "/las-vegas-relocation-guide"}>
          <a href="/neighborhood">Areas</a>
          <ul class="dropdown">
            <li><a href="/neighborhood">Pewter Valley Estates</a></li>
            <li><a href="/silverado-ranch">Silverado Ranch (Henderson)</a></li>
            <li><a href="/southwest-las-vegas">Southwest Las Vegas</a></li>
            <li><a href="/neighborhood-guide">Neighborhood Guide</a></li>
            <li><a href="/photos">Community Photos</a></li>
            <li><a href="/las-vegas-relocation-guide">Relocation Guide</a></li>
            <li><a href="/pewter-valley-estates/amenities">Nearby amenities (Pewter)</a></li>
            <li><a href="/silverado-ranch/getting-around">Commute &amp; transport</a></li>
            <li><a href="/silverado-ranch/attractions">Attractions &amp; day trips</a></li>
            <li><a href="/silverado-ranch/history">Silverado Ranch history</a></li>
          </ul>
        </li>
        <li class:active={page.url.pathname === "/about" || page.url.pathname === "/dr-jan-duffy"}>
          <a href="/about">About</a>
        </li>
        <li class:active={page.url.pathname === "/contact"}>
          <a href="/contact">Contact</a>
        </li>
      </ul>
    </nav>

    <!-- CTA Button -->
    <a href={`tel:${SITE_CONFIG.phoneTel}`} class="header-cta">
      <span class="cta-icon">📞</span>
      <span class="cta-text">{SITE_CONFIG.phone}</span>
    </a>

    <!-- Mobile Menu Toggle -->
    <button class="mobile-toggle" onclick={toggleMenu} aria-label="Toggle menu">
      <span class="hamburger" class:open={mobileMenuOpen}></span>
    </button>
  </div>

  <!-- Mobile Navigation -->
  {#if mobileMenuOpen}
    <nav class="mobile-nav" transition:slide={{ duration: 200 }}>
      <ul>
        <li><a href="/" onclick={closeMenu}>Home</a></li>
        <li class="mobile-section">
          <span class="section-title">Buy a Home</span>
          <ul>
            <li><a href="/homes-for-sale" onclick={closeMenu}>Homes for Sale</a></li>
            <li><a href="/buy-a-home" onclick={closeMenu}>Buyer's Guide</a></li>
            <li><a href="/buyer-checklist" onclick={closeMenu}>Buyer Checklist</a></li>
            <li><a href="/listings" onclick={closeMenu}>All Listings</a></li>
            <li><a href="/investment-properties" onclick={closeMenu}>Investment Properties</a></li>
          </ul>
        </li>
        <li class="mobile-section">
          <span class="section-title">Sell Your Home</span>
          <ul>
            <li><a href="/sell-your-home" onclick={closeMenu}>Sell Your Home</a></li>
            <li><a href="/selling-checklist" onclick={closeMenu}>Selling Checklist</a></li>
            <li><a href="/home-valuation" onclick={closeMenu}>Free Home Valuation</a></li>
            <li><a href="/market-analysis" onclick={closeMenu}>Market Analysis</a></li>
          </ul>
        </li>
        <li class="mobile-section">
          <span class="section-title">Explore Areas</span>
          <ul>
            <li><a href="/neighborhood" onclick={closeMenu}>Pewter Valley Estates</a></li>
            <li><a href="/silverado-ranch" onclick={closeMenu}>Silverado Ranch (Henderson)</a></li>
            <li><a href="/southwest-las-vegas" onclick={closeMenu}>Southwest Las Vegas</a></li>
            <li><a href="/neighborhood-guide" onclick={closeMenu}>Neighborhood Guide</a></li>
            <li><a href="/las-vegas-relocation-guide" onclick={closeMenu}>Relocation Guide</a></li>
            <li><a href="/photos" onclick={closeMenu}>Community Photos</a></li>
            <li><a href="/pewter-valley-estates/amenities" onclick={closeMenu}>Nearby amenities (Pewter)</a></li>
            <li><a href="/silverado-ranch/getting-around" onclick={closeMenu}>Commute &amp; transport</a></li>
            <li><a href="/silverado-ranch/attractions" onclick={closeMenu}>Attractions &amp; day trips</a></li>
            <li><a href="/silverado-ranch/history" onclick={closeMenu}>Silverado Ranch history</a></li>
          </ul>
        </li>
        <li><a href="/about" onclick={closeMenu}>About Dr. Jan Duffy</a></li>
        <li><a href="/faq" onclick={closeMenu}>FAQ</a></li>
        <li><a href="/contact" onclick={closeMenu}>Contact</a></li>
      </ul>
      <a href={`tel:${SITE_CONFIG.phoneTel}`} class="mobile-cta" onclick={closeMenu}>
        📞 Call {SITE_CONFIG.phone}
      </a>
    </nav>
  {/if}
</header>

<style>
  .site-header {
    position: sticky;
    top: 0;
    z-index: 1000;
    background: white;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }

  .header-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 1.5rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 70px;
  }

  .brand {
    display: flex;
    flex-direction: column;
    text-decoration: none;
    gap: 0;
  }

  .brand-name {
    font-size: 1.25rem;
    font-weight: 700;
    color: #1e3a8a;
    line-height: 1.2;
  }

  .brand-tagline {
    font-size: 0.75rem;
    color: #64748b;
  }

  /* Desktop Navigation */
  .desktop-nav {
    display: none;
  }

  .desktop-nav ul {
    display: flex;
    list-style: none;
    margin: 0;
    padding: 0;
    gap: 0.25rem;
  }

  .desktop-nav > ul > li {
    position: relative;
  }

  .desktop-nav > ul > li > a {
    display: block;
    padding: 0.75rem 1rem;
    color: #374151;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.9rem;
    transition: color 0.2s;
    border-radius: 0.375rem;
  }

  .desktop-nav > ul > li > a:hover,
  .desktop-nav > ul > li.active > a {
    color: #1e3a8a;
    background: #f1f5f9;
  }

  /* Dropdown */
  .dropdown {
    display: none;
    position: absolute;
    top: 100%;
    left: 0;
    background: white;
    min-width: 200px;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.15);
    border-radius: 0.5rem;
    padding: 0.5rem 0;
    z-index: 100;
  }

  .has-dropdown:hover .dropdown {
    display: block;
  }

  .dropdown li a {
    display: block;
    padding: 0.625rem 1.25rem;
    color: #374151;
    text-decoration: none;
    font-size: 0.875rem;
    transition: all 0.2s;
  }

  .dropdown li a:hover {
    background: #f1f5f9;
    color: #1e3a8a;
  }

  /* Header CTA */
  .header-cta {
    display: none;
    align-items: center;
    gap: 0.5rem;
    padding: 0.625rem 1.25rem;
    background: #16B286;
    color: white;
    text-decoration: none;
    border-radius: 0.5rem;
    font-weight: 600;
    font-size: 0.9rem;
    transition: all 0.2s;
  }

  .header-cta:hover {
    background: #0D8A5B;
    transform: translateY(-1px);
  }

  .cta-icon {
    font-size: 1rem;
  }

  /* Mobile Toggle */
  .mobile-toggle {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 40px;
    height: 40px;
    background: none;
    border: none;
    cursor: pointer;
    padding: 0;
  }

  .hamburger {
    position: relative;
    width: 24px;
    height: 2px;
    background: #374151;
    transition: all 0.3s;
  }

  .hamburger::before,
  .hamburger::after {
    content: '';
    position: absolute;
    width: 24px;
    height: 2px;
    background: #374151;
    transition: all 0.3s;
  }

  .hamburger::before {
    top: -7px;
  }

  .hamburger::after {
    top: 7px;
  }

  .hamburger.open {
    background: transparent;
  }

  .hamburger.open::before {
    top: 0;
    transform: rotate(45deg);
  }

  .hamburger.open::after {
    top: 0;
    transform: rotate(-45deg);
  }

  /* Mobile Navigation */
  .mobile-nav {
    position: absolute;
    top: 70px;
    left: 0;
    right: 0;
    background: white;
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.15);
    padding: 1rem;
    max-height: calc(100vh - 70px);
    overflow-y: auto;
  }

  .mobile-nav > ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }

  .mobile-nav > ul > li > a {
    display: block;
    padding: 0.875rem 1rem;
    color: #1e3a8a;
    text-decoration: none;
    font-weight: 600;
    font-size: 1rem;
    border-bottom: 1px solid #e2e8f0;
  }

  .mobile-section {
    border-bottom: 1px solid #e2e8f0;
    padding: 0.875rem 0;
  }

  .section-title {
    display: block;
    padding: 0 1rem 0.5rem;
    color: #64748b;
    font-size: 0.75rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }

  .mobile-section ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }

  .mobile-section ul li a {
    display: block;
    padding: 0.625rem 1rem 0.625rem 1.5rem;
    color: #374151;
    text-decoration: none;
    font-size: 0.95rem;
  }

  .mobile-cta {
    display: block;
    margin-top: 1rem;
    padding: 1rem;
    background: #16B286;
    color: white;
    text-decoration: none;
    text-align: center;
    border-radius: 0.5rem;
    font-weight: 700;
    font-size: 1rem;
  }

  /* Responsive */
  @media (min-width: 1024px) {
    .desktop-nav {
      display: block;
    }

    .header-cta {
      display: flex;
    }

    .mobile-toggle {
      display: none;
    }

    .mobile-nav {
      display: none;
    }
  }

  @media (max-width: 480px) {
    .brand-name {
      font-size: 1.1rem;
    }

    .cta-text {
      display: none;
    }
  }
</style>
